apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::305662172920:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-H5ER7U8NONPZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::305662172920:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-23T20:21:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2462"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d1f41529-3b62-4512-9270-b1716d62a36c
